window.streams = {
    timeRefresh: 10000,
    stations: [
        {
            name: "Radio Power",
            hash: "Radiopower",
            description: "Con el poder de los clásicos",
            logo: "",
            album: "assets1/radio_cover.webp",
            cover: "",
            api: "https://api.zeno.fm/mounts/metadata/subscribe/dlvtl3hthyxvv",
            stream_url: "https://stream.zeno.fm/dlvtl3hthyxvv",
            tv_url: "",
            server: "",
            apps: {
                android: "",
                ios: "",
            },
        },
        {
            name: "URBANA",
            hash: "URBANA",
            description: "",
            logo: "",
            album: "assets1/radio_cover2.webp",
            cover: "",
            api: "https://api.zeno.fm/mounts/metadata/subscribe/cxf1r8zukyhuv",
            stream_url: "https://stream.zeno.fm/cxf1r8zukyhuv",
            tv_url: "",
            server: "",
            apps: {
                android: "#",
                ios: "#",
            },
        },
        {
            name: "SALSA",
            hash: "SALSA",
            description: "",
            logo: "",
            album: "assets1/radio_cover3.webp",
            cover: "",
            api: "https://api.zeno.fm/mounts/metadata/subscribe/v99hvs8ojo3tv",
            stream_url: "https://stream.zeno.fm/v99hvs8ojo3tv",
            server: "spotify",
            apps: {
                android: "",
                ios: "",
            },
        },
        {
            name: "VALLENATO",
            hash: "VALLENATO",
            description: "",
            logo: "",
            album: "assets1/radio_cover4.webp",
            cover: "",
            api: "https://api.zeno.fm/mounts/metadata/subscribe/w3hzwbk99aatv",
            stream_url: "https://stream.zeno.fm/w3hzwbk99aatv",
            tv_url: "",
            server: "",
            apps: {
                android: "",
                ios: "",
            },
        },
    ],
};